version: "3"

services:
  ems-backend:
    container_name: ems-backend
    build:
      context: ./ems-backend
      dockerfile: Dockerfile
    image: ems-backend:latest
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ems
      DB_PASSWORD: ems
      DB_NAME: ems
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db

# Production
  ems-frontend:
    container_name: ems-frontend
    build:
      context: ./ems-frontend
      dockerfile: Dockerfile
    image: ems-frontend:latest
    ports:
      - "3000:80"

# Development
  # ems-frontend:
  #   container_name: ems-frontend
  #   build:
  #     context: ./ems-frontend
  #     dockerfile: Dockerfile-dev
  #   image: ems-frontend:latest
  #   volumes:
  #     - ./ems-frontend:/application
  #   ports:
  #     - "3000:3000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ems
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ems
      MYSQL_PASSWORD: ems
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ems-db-data:/var/lib/mysql

  postgres:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:16.1.1
    depends_on:
      - postgres
    container_name: ems-keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    ports:
      - "4000:8080"
    restart: always

volumes:
  ems-db-data:
  keycloak-db-data:
