version: "3"

services:
  ems-backend:
    container_name: ems-backend
    build:
      context: ./ems-backend
      dockerfile: Dockerfile
    image: ems-backend:latest
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ems
      DB_PASSWORD: ems
      DB_NAME: ems
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db

# Production
  ems-frontend:
    container_name: ems-frontend
    build:
      context: ./ems-frontend
      dockerfile: Dockerfile
    image: ems-frontend:latest
    ports:
      - "3000:80"

# Development
  # ems-frontend:
  #   container_name: ems-frontend
  #   build:
  #     context: ./ems-frontend
  #     dockerfile: Dockerfile-dev
  #   image: ems-frontend:latest
  #   volumes:
  #     - ./ems-frontend:/application
  #   ports:
  #     - "3000:3000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ems
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ems
      MYSQL_PASSWORD: ems
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ems-db-data:/var/lib/mysql

  postgresql:
    image: bitnami/postgresql:14.4.0
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_PASSWORD: bn_keycloak
      POSTGRESQL_USERNAME: bn_keycloak
      POSTGRESQL_DATABASE: bitnami_keycloak
    volumes:
      - keycloak-db-data:/bitnami/postgresql

  keycloak:
    image: bitnami/keycloak:18.0.1
    depends_on:
      - postgresql
    container_name: ems-keycloak
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_DATABASE_PASSWORD: bn_keycloak
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "5000:8080"
    restart: always

volumes:
  ems-db-data:
  keycloak-db-data:
